### ISSUE TITLE
How this project ?

### ISSUE THREAD

**Issue by leonardo403** [getify/concrete-syntax-tree#5]
Hello guys,

This project still continue ?

**Comment by getify** [comment]
I am working on a fork of esprima implementing a CST format. The discussions here were not really going in a productive direction, so I'm just specifying through implementing.

**Comment by ericelliott** [comment]
Just about every successful format I've ever heard of started out as a benevolent dictator's pet project, and only became standardized after there was an existing implementation.

This is normal. =) See [design by committee](http://en.wikipedia.org/wiki/Design_by_committee)

**Comment by leonardo403** [comment]
Hello guys,

Very much thank for  response, because going learning more about this
implementation.

On Fri, Nov 14, 2014 at 11:58 PM, Eric Elliott notifications@github.com
wrote:

> Just about every successful format I've ever heard of started out as a
> benevolent dictator's pet project, and only became standardized after there
> was an existing implementation.
> 
> This is normal. =)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/getify/concrete-syntax-tree/issues/5#issuecomment-63155344
> .

## 

_Leonardo Lima_
_Web developer Jr._

Fone:  _(051) 8336-5081_
Github: https://github.com/leonardo403
Google+: https://plus.google.com/u/0/+LeonardoLimawebdev/
About.me: http://about.me/leonardolima
Twitter: https://twitter.com/Leonardo403Br
